import Head from "next/head";
import { Navbar, Statistics, Stake, MyStakes } from "../components";
import config from "../constant/config";

export default function Home() {

  console.log(config);
  return (
    <div>
      <Head>
        <title>$RAPID Stake App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <div className="flex flex-col gap-4 w-full h-full container max-w-[1200px] p-4 mx-auto">
        <Navbar />
        <Statistics />
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <Stake />
          <MyStakes />
        </div>
      </div>
    </div>
  );
}
